-- ==============================================================================
-- Supabase Schema for GaGa Housie Authentication
-- Target Table: user_auth
-- Columns: fullname, email, phone (10 digits), password, status, role
-- Default Roles: 'admin' for admin@gmail.com, 'user' for app registrations
-- ==============================================================================

-- 1. Create the user_auth table in the public schema
CREATE TABLE IF NOT EXISTS public.user_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone VARCHAR(10) UNIQUE NOT NULL CHECK (phone ~ '^[0-9]{10}$'),
    password TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure status and role columns exist if table was created previously
ALTER TABLE public.user_auth 
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';

ALTER TABLE public.user_auth 
    ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user';

-- 2. Grant table and schema permissions to anon and authenticated roles
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.user_auth TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.user_auth ENABLE ROW LEVEL SECURITY;

-- 4. Policy: Allow read queries for authentication
DROP POLICY IF EXISTS "Allow public read for auth" ON public.user_auth;
CREATE POLICY "Allow public read for auth" 
    ON public.user_auth 
    FOR SELECT 
    TO anon, authenticated
    USING (true);

-- 5. Policy: Allow user registration insert (default role: 'user')
DROP POLICY IF EXISTS "Allow public insert for registration" ON public.user_auth;
CREATE POLICY "Allow public insert for registration" 
    ON public.user_auth 
    FOR INSERT 
    TO anon, authenticated
    WITH CHECK (true);

-- 6. Policy: Allow update
DROP POLICY IF EXISTS "Allow users to update their auth" ON public.user_auth;
CREATE POLICY "Allow users to update their auth" 
    ON public.user_auth 
    FOR UPDATE 
    TO anon, authenticated
    USING (true);

-- 7. Insert or update default admin account (role: 'admin')
INSERT INTO public.user_auth (fullname, email, phone, password, status, role)
VALUES ('GaGa Admin', 'admin@gmail.com', '9876543210', '1234', 'active', 'admin')
ON CONFLICT (email) DO UPDATE 
SET role = 'admin', status = 'active';

-- Ensure any existing admin@gmail.com account is updated to 'admin' role
UPDATE public.user_auth SET role = 'admin' WHERE email = 'admin@gmail.com';


-- ==============================================================================
-- 2. TABLE: tickets (Admin Created & User Upcoming Draw Tickets)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT UNIQUE NOT NULL,                       -- e.g. GAGA26000001
    ticket_title TEXT NOT NULL DEFAULT 'GaGa Housie Draw',
    draw_date TEXT NOT NULL,                             -- e.g. 25/09/2026
    draw_time TEXT NOT NULL,                             -- e.g. 07:00 PM
    price TEXT NOT NULL DEFAULT '₹20',                    -- e.g. ₹20
    total_prize TEXT NOT NULL DEFAULT '₹75000',           -- Sum of all prize tiers
    prizes JSONB NOT NULL DEFAULT '[]'::jsonb,           -- JSON array of prize tiers
    status TEXT NOT NULL DEFAULT 'Active',                -- Active / Completed / Cancelled
    created_by TEXT,                                     -- Admin email
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Grants for tickets table
GRANT ALL ON TABLE public.tickets TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Policies for tickets:
-- Allow anyone (regular users + admin) to read tickets
DROP POLICY IF EXISTS "Allow read tickets" ON public.tickets;
CREATE POLICY "Allow read tickets" 
    ON public.tickets 
    FOR SELECT 
    TO anon, authenticated
    USING (true);

-- Allow inserting new tickets (Admin create ticket)
DROP POLICY IF EXISTS "Allow insert tickets" ON public.tickets;
CREATE POLICY "Allow insert tickets" 
    ON public.tickets 
    FOR INSERT 
    TO anon, authenticated
    WITH CHECK (true);

-- Allow updating tickets
DROP POLICY IF EXISTS "Allow update tickets" ON public.tickets;
CREATE POLICY "Allow update tickets" 
    ON public.tickets 
    FOR UPDATE 
    TO anon, authenticated
    USING (true);

-- Allow deleting tickets
DROP POLICY IF EXISTS "Allow delete tickets" ON public.tickets;
CREATE POLICY "Allow delete tickets" 
    ON public.tickets 
    FOR DELETE 
    TO anon, authenticated
    USING (true);


-- ==============================================================================
-- 3. SEED INITIAL UPCOMING TICKETS (with Requested 7 Prize Tiers)
-- ==============================================================================
INSERT INTO public.tickets (ticket_id, ticket_title, draw_date, draw_time, price, total_prize, status, prizes)
VALUES 
(
    'GAGA26000001',
    'Ticket 1',
    '25/09/2026',
    '07:00 PM',
    '₹20',
    '₹75000',
    'Active',
    '[
        {"name": "Housefull", "price": "₹50000"},
        {"name": "1st Line", "price": "₹3000"},
        {"name": "2nd Line", "price": "₹3000"},
        {"name": "3rd Line", "price": "₹3000"},
        {"name": "4th Corner", "price": "₹3000"},
        {"name": "Quick Five", "price": "₹3000"},
        {"name": "3 Ticket Quick", "price": "₹10000"}
    ]'::jsonb
),
(
    'GAGA26000002',
    'Ticket 2',
    '26/09/2026',
    '08:00 PM',
    '₹25',
    '₹95000',
    'Active',
    '[
        {"name": "Housefull", "price": "₹60000"},
        {"name": "1st Line", "price": "₹4000"},
        {"name": "2nd Line", "price": "₹4000"},
        {"name": "3rd Line", "price": "₹4000"},
        {"name": "4th Corner", "price": "₹5000"},
        {"name": "Quick Five", "price": "₹5000"},
        {"name": "3 Ticket Quick 10", "price": "₹15000"}
    ]'::jsonb
),
(
    'GAGA26000003',
    'Ticket 3',
    '27/09/2026',
    '07:30 PM',
    '₹30',
    '₹110000',
    'Active',
    '[
        {"name": "Housefull", "price": "₹75000"},
        {"name": "1st Line", "price": "₹5000"},
        {"name": "2nd Line", "price": "₹5000"},
        {"name": "3rd Line", "price": "₹5000"},
        {"name": "4th Corner", "price": "₹5500"},
        {"name": "Quick Five", "price": "₹5500"},
        {"name": "3 Ticket Quick", "price": "₹18000"}
    ]'::jsonb
),
(
    'GAGA26000004',
    'Ticket 4',
    '28/09/2026',
    '09:00 PM',
    '₹50',
    '₹150000',
    'Active',
    '[
        {"name": "Housefull", "price": "₹90000"},
        {"name": "1st Line", "price": "₹6000"},
        {"name": "2nd Line", "price": "₹6000"},
        {"name": "3rd Line", "price": "₹6000"},
        {"name": "4th Corner", "price": "₹7000"},
        {"name": "Quick Five", "price": "₹7000"},
        {"name": "3 Ticket Quick 10", "price": "₹25000"}
    ]'::jsonb
)
ON CONFLICT (ticket_id) DO NOTHING;


-- ==============================================================================
-- 4. TABLE: tambola_tickets (Housie / Tambola Grids Linked to Main Draw Tickets)
-- ==============================================================================
-- Relation: Foreign key `ticket_id` references `tickets.ticket_id` with ON DELETE CASCADE.
-- Unique Relation: (ticket_id, sl_no) ensures each SL No (1 to 6) is unique per main draw ticket.
CREATE TABLE IF NOT EXISTS public.tambola_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT NOT NULL REFERENCES public.tickets(ticket_id) ON DELETE CASCADE,
    sl_no INT NOT NULL CHECK (sl_no >= 1 AND sl_no <= 12),
    serial_number TEXT NOT NULL,                                  -- e.g. 'SR-101'
    unique_code TEXT NOT NULL,                                    -- e.g. 'GH-8902'
    player_name TEXT NOT NULL DEFAULT 'Available',
    ticket_data JSONB NOT NULL DEFAULT '[]'::jsonb,              -- 3x9 grid matrix: [[1, null, 23...], ...]
    status TEXT NOT NULL DEFAULT 'Available',                     -- 'Available' / 'Booked' / 'Selected'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_ticket_sl UNIQUE (ticket_id, sl_no)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.tambola_tickets ENABLE ROW LEVEL SECURITY;

-- Grants for tambola_tickets table
GRANT ALL ON TABLE public.tambola_tickets TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Index for fast lookup by main ticket ID and composite (ticket_id, sl_no)
CREATE INDEX IF NOT EXISTS idx_tambola_tickets_ticket_id ON public.tambola_tickets(ticket_id);
CREATE INDEX IF NOT EXISTS idx_tambola_tickets_ticket_sl ON public.tambola_tickets(ticket_id, sl_no);

-- Policies for tambola_tickets:
-- Allow anyone (users and admins) to view Tambola tickets
DROP POLICY IF EXISTS "Allow read tambola_tickets" ON public.tambola_tickets;
CREATE POLICY "Allow read tambola_tickets" 
    ON public.tambola_tickets 
    FOR SELECT 
    TO anon, authenticated
    USING (true);

-- Allow inserting Tambola tickets (admin configures numbers)
DROP POLICY IF EXISTS "Allow insert tambola_tickets" ON public.tambola_tickets;
CREATE POLICY "Allow insert tambola_tickets" 
    ON public.tambola_tickets 
    FOR INSERT 
    TO anon, authenticated
    WITH CHECK (true);

-- Allow updating Tambola tickets
DROP POLICY IF EXISTS "Allow update tambola_tickets" ON public.tambola_tickets;
CREATE POLICY "Allow update tambola_tickets" 
    ON public.tambola_tickets 
    FOR UPDATE 
    TO anon, authenticated
    USING (true);

-- Allow deleting Tambola tickets
DROP POLICY IF EXISTS "Allow delete tambola_tickets" ON public.tambola_tickets;
CREATE POLICY "Allow delete tambola_tickets" 
    ON public.tambola_tickets 
    FOR DELETE 
    TO anon, authenticated
    USING (true);

-- Sample Seed Tambola Tickets for GAGA26000001 (SL 1 to 6)
INSERT INTO public.tambola_tickets (ticket_id, sl_no, serial_number, unique_code, player_name, ticket_data, status)
VALUES
(
    'GAGA26000001', 1, 'SR-101', 'GH-8901', 'Available',
    '[[4, null, 23, null, 41, 56, null, 72, null], [null, 15, null, 37, 49, null, 63, null, 85], [8, 19, null, null, null, 59, 68, 77, null]]'::jsonb,
    'Available'
),
(
    'GAGA26000001', 2, 'SR-102', 'GH-8902', 'Available',
    '[[null, 12, 25, null, 44, null, 61, 75, null], [2, null, null, 33, 48, 52, null, null, 88], [7, 18, null, 39, null, null, 69, 79, null]]'::jsonb,
    'Available'
),
(
    'GAGA26000001', 3, 'SR-103', 'GH-8903', 'Available',
    '[[5, null, 21, 32, null, 54, null, 71, null], [null, 16, null, null, 46, 58, 65, null, 82], [9, null, 28, 36, null, null, null, 78, 89]]'::jsonb,
    'Available'
),
(
    'GAGA26000001', 4, 'SR-104', 'GH-8904', 'Available',
    '[[1, 14, null, null, 42, null, 64, null, 83], [null, null, 26, 35, null, 55, 67, 74, null], [6, 17, null, 38, 47, null, null, null, 87]]'::jsonb,
    'Available'
),
(
    'GAGA26000001', 5, 'SR-105', 'GH-8905', 'Available',
    '[[3, null, 22, null, 43, 51, null, 73, null], [null, 11, null, 31, null, null, 62, 76, 84], [null, 19, 29, null, 45, 57, null, null, 90]]'::jsonb,
    'Available'
),
(
    'GAGA26000001', 6, 'SR-106', 'GH-8906', 'Available',
    '[[null, 13, 24, null, 40, null, 66, null, 81], [2, null, null, 34, null, 53, null, 70, 86], [8, null, 27, 39, null, 59, null, 79, null]]'::jsonb,
    'Available'
)
ON CONFLICT (ticket_id, sl_no) DO NOTHING;


-- ==============================================================================
-- 5. CRITICAL: Reload PostgREST schema cache
-- ==============================================================================
NOTIFY pgrst, 'reload schema';

-- Verification queries:
-- SELECT id, fullname, email, phone, status, role, created_at FROM public.user_auth;
-- SELECT id, ticket_id, ticket_title, draw_date, draw_time, price, total_prize, prizes, status FROM public.tickets;
-- SELECT id, ticket_id, sl_no, serial_number, unique_code, player_name, ticket_data, status FROM public.tambola_tickets;
