-- ==============================================================================
-- Supabase Schema for GaGa Housie Authentication
-- Target Table: user_auth
-- Columns: fullname, email, phone (10 digits), password, status, role
-- Default Roles: 'admin' for admin@gmail.com, 'user' for app registrations
-- ==============================================================================

-- 1. Create the user_auth table in the public schema
CREATE TABLE IF NOT EXISTS public.user_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone VARCHAR(10) UNIQUE NOT NULL CHECK (phone ~ '^[0-9]{10}$'),
    password TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure status and role columns exist if table was created previously
ALTER TABLE public.user_auth 
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';

ALTER TABLE public.user_auth 
    ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user';

-- 2. Grant table and schema permissions to anon and authenticated roles
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.user_auth TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.user_auth ENABLE ROW LEVEL SECURITY;

-- 4. Policy: Allow read queries for authentication
DROP POLICY IF EXISTS "Allow public read for auth" ON public.user_auth;
CREATE POLICY "Allow public read for auth" 
    ON public.user_auth 
    FOR SELECT 
    TO anon, authenticated
    USING (true);

-- 5. Policy: Allow user registration insert (default role: 'user')
DROP POLICY IF EXISTS "Allow public insert for registration" ON public.user_auth;
CREATE POLICY "Allow public insert for registration" 
    ON public.user_auth 
    FOR INSERT 
    TO anon, authenticated
    WITH CHECK (true);

-- 6. Policy: Allow update
DROP POLICY IF EXISTS "Allow users to update their auth" ON public.user_auth;
CREATE POLICY "Allow users to update their auth" 
    ON public.user_auth 
    FOR UPDATE 
    TO anon, authenticated
    USING (true);

-- 7. Insert or update default admin account (role: 'admin')
INSERT INTO public.user_auth (fullname, email, phone, password, status, role)
VALUES ('GaGa Admin', 'admin@gmail.com', '9876543210', '1234', 'active', 'admin')
ON CONFLICT (email) DO UPDATE 
SET role = 'admin', status = 'active';

-- Ensure any existing admin@gmail.com account is updated to 'admin' role
UPDATE public.user_auth SET role = 'admin' WHERE email = 'admin@gmail.com';


-- ==============================================================================
-- 2. TABLE: tickets (Admin Created & User Upcoming Draw Tickets)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT UNIQUE NOT NULL,                       -- e.g. GAGA26000001
    ticket_title TEXT NOT NULL DEFAULT 'GaGa Housie Draw',
    draw_date TEXT NOT NULL,                             -- e.g. 25/09/2026
    draw_time TEXT NOT NULL,                             -- e.g. 07:00 PM
    price TEXT NOT NULL DEFAULT '₹20',                    -- e.g. ₹20
    total_prize TEXT NOT NULL DEFAULT '₹75000',           -- Sum of all prize tiers
    prizes JSONB NOT NULL DEFAULT '[]'::jsonb,           -- JSON array of prize tiers
    status TEXT NOT NULL DEFAULT 'Active',                -- Active / Completed / Cancelled
    created_by TEXT,                                     -- Admin email
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Grants for tickets table
GRANT ALL ON TABLE public.tickets TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Policies for tickets:
-- Allow anyone (regular users + admin) to read tickets
DROP POLICY IF EXISTS "Allow read tickets" ON public.tickets;
CREATE POLICY "Allow read tickets" 
    ON public.tickets 
    FOR SELECT 
    TO anon, authenticated
    USING (true);

-- Allow inserting new tickets (Admin create ticket)
DROP POLICY IF EXISTS "Allow insert tickets" ON public.tickets;
CREATE POLICY "Allow insert tickets" 
    ON public.tickets 
    FOR INSERT 
    TO anon, authenticated
    WITH CHECK (true);

-- Allow updating tickets
DROP POLICY IF EXISTS "Allow update tickets" ON public.tickets;
CREATE POLICY "Allow update tickets" 
    ON public.tickets 
    FOR UPDATE 
    TO anon, authenticated
    USING (true);

-- Allow deleting tickets
DROP POLICY IF EXISTS "Allow delete tickets" ON public.tickets;
CREATE POLICY "Allow delete tickets" 
    ON public.tickets 
    FOR DELETE 
    TO anon, authenticated
    USING (true);


-- ==============================================================================
-- 3. SEED INITIAL UPCOMING TICKETS (with Requested 7 Prize Tiers)
-- ==============================================================================
INSERT INTO public.tickets (ticket_id, ticket_title, draw_date, draw_time, price, total_prize, status, prizes)
VALUES 
(
    'GAGA26000001',
    'Ticket 1',
    '25/09/2026',
    '07:00 PM',
    '₹20',
    '₹75000',
    'Active',
    '[
        {"name": "Housefull", "price": "₹50000"},
        {"name": "1st Line", "price": "₹3000"},
        {"name": "2nd Line", "price": "₹3000"},
        {"name": "3rd Line", "price": "₹3000"},
        {"name": "4th Corner", "price": "₹3000"},
        {"name": "Quick Five", "price": "₹3000"},
        {"name": "3 Ticket Quick", "price": "₹10000"}
    ]'::jsonb
),
(
    'GAGA26000002',
    'Ticket 2',
    '26/09/2026',
    '08:00 PM',
    '₹25',
    '₹95000',
    'Active',
    '[
        {"name": "Housefull", "price": "₹60000"},
        {"name": "1st Line", "price": "₹4000"},
        {"name": "2nd Line", "price": "₹4000"},
        {"name": "3rd Line", "price": "₹4000"},
        {"name": "4th Corner", "price": "₹5000"},
        {"name": "Quick Five", "price": "₹5000"},
        {"name": "3 Ticket Quick 10", "price": "₹15000"}
    ]'::jsonb
),
(
    'GAGA26000003',
    'Ticket 3',
    '27/09/2026',
    '07:30 PM',
    '₹30',
    '₹110000',
    'Active',
    '[
        {"name": "Housefull", "price": "₹75000"},
        {"name": "1st Line", "price": "₹5000"},
        {"name": "2nd Line", "price": "₹5000"},
        {"name": "3rd Line", "price": "₹5000"},
        {"name": "4th Corner", "price": "₹5500"},
        {"name": "Quick Five", "price": "₹5500"},
        {"name": "3 Ticket Quick", "price": "₹18000"}
    ]'::jsonb
),
(
    'GAGA26000004',
    'Ticket 4',
    '28/09/2026',
    '09:00 PM',
    '₹50',
    '₹150000',
    'Active',
    '[
        {"name": "Housefull", "price": "₹90000"},
        {"name": "1st Line", "price": "₹6000"},
        {"name": "2nd Line", "price": "₹6000"},
        {"name": "3rd Line", "price": "₹6000"},
        {"name": "4th Corner", "price": "₹7000"},
        {"name": "Quick Five", "price": "₹7000"},
        {"name": "3 Ticket Quick 10", "price": "₹25000"}
    ]'::jsonb
)
ON CONFLICT (ticket_id) DO NOTHING;


-- ==============================================================================
-- 4. CRITICAL: Reload PostgREST schema cache
-- ==============================================================================
NOTIFY pgrst, 'reload schema';

-- Verification queries:
-- SELECT id, fullname, email, phone, status, role, created_at FROM public.user_auth;
-- SELECT id, ticket_id, ticket_title, draw_date, draw_time, price, total_prize, prizes, status FROM public.tickets;
