-- ==============================================================================
-- Supabase Schema for GaGa Housie Authentication
-- Target Table: user_auth
-- Columns: fullname, email, phone (10 digits), password, status, role
-- Default Roles: 'admin' for admin@gmail.com, 'user' for app registrations
-- ==============================================================================

-- 1. Create the user_auth table in the public schema
CREATE TABLE IF NOT EXISTS public.user_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone VARCHAR(10) UNIQUE NOT NULL CHECK (phone ~ '^[0-9]{10}$'),
    password TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    role TEXT NOT NULL DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure status and role columns exist if table was created previously
ALTER TABLE public.user_auth 
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';

ALTER TABLE public.user_auth 
    ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user';

-- 2. Grant table and schema permissions to anon and authenticated roles
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.user_auth TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.user_auth ENABLE ROW LEVEL SECURITY;

-- 4. Policy: Allow read queries for authentication
DROP POLICY IF EXISTS "Allow public read for auth" ON public.user_auth;
CREATE POLICY "Allow public read for auth" 
    ON public.user_auth 
    FOR SELECT 
    TO anon, authenticated
    USING (true);

-- 5. Policy: Allow user registration insert (default role: 'user')
DROP POLICY IF EXISTS "Allow public insert for registration" ON public.user_auth;
CREATE POLICY "Allow public insert for registration" 
    ON public.user_auth 
    FOR INSERT 
    TO anon, authenticated
    WITH CHECK (true);

-- 6. Policy: Allow update
DROP POLICY IF EXISTS "Allow users to update their auth" ON public.user_auth;
CREATE POLICY "Allow users to update their auth" 
    ON public.user_auth 
    FOR UPDATE 
    TO anon, authenticated
    USING (true);

-- 7. Insert or update default admin account (role: 'admin')
INSERT INTO public.user_auth (fullname, email, phone, password, status, role)
VALUES ('GaGa Admin', 'admin@gmail.com', '9876543210', '1234', 'active', 'admin')
ON CONFLICT (email) DO UPDATE 
SET role = 'admin', status = 'active';

-- Ensure any existing admin@gmail.com account is updated to 'admin' role
UPDATE public.user_auth SET role = 'admin' WHERE email = 'admin@gmail.com';

-- 8. CRITICAL: Reload PostgREST schema cache so columns are immediately active
NOTIFY pgrst, 'reload schema';

-- Verification query:
-- SELECT id, fullname, email, phone, status, role, created_at FROM public.user_auth;
